### ISSUE TITLE
Event handler firing twice?

### ISSUE THREAD

**Issue by tpluscode** [PolymerElements/test-fixture#27]
Hi. I'm using `<test-fixture>` to [test my component](https://github.com/tpluscode/ld-navigation/blob/master/test/ld-navigator-tests.html). 

When you run my tests with `wct`, you'll see that the test in line 77 fails in previous test's event listener (line 69) unless I explicitly remove the handler. Why is that? The `document.getElementById('EmptyNavigator').restore()` in `afterEach` has no effect here. On the other hand the handler on line 58 never gets fired twice. 

Please help me understand my mistake.

**Comment by cdata** [comment]
Thanks for filing an issue. We need to see a reduced test case in order to verify that there is a problem. Please re-open the issue when you have a test case, and consult our [contribution guidelines](../blob/master/CONTRIBUTING.md) for more details on filing issues!
