### ISSUE TITLE
NPM package name conflict

### ISSUE THREAD

**Issue by BenoitPerrot** [PolymerElements/test-fixture#28]
Hello,

A different npm package having the same name (ie test-fixture) is already registered on npmjs.org.
This is somewhat problematic, as it makes the getting of <test-fixture> slightly more difficult: the only way to get the npm package is to point at it via a git url. This is generally fine but in some environment , it is desirable to avoid accessing git repositories and instead rely on some caching proxy (eg nexus), and for that the origin point (npmjs site) must host the "expected package". As another yet minor issue, the dependency information on npmjs site is also gotten wrong (web-component-tester is said to use the other, "wrong" test-fixture).

I realize how difficult it can be to change the name of the package, so probably another solution should be devised (having the other package removed, as not having been updated for 2 years, etc.) -  I just wanted you to know about the issue, and see if you could devise a solution.

**Comment by justinfagnani** [comment]
we'll register this as @polymer/test-fixture

**Comment by justinfagnani** [comment]
Sorry, it was already published here: https://www.npmjs.com/package/@polymer/test-fixture

We'll work on updating to the real version numbers soon.

**Comment by BenoitPerrot** [comment]
Thanks!
