### ISSUE TITLE
fixture() throws 'Error stamping [object Object] NotSupportedError'

### ISSUE THREAD

**Issue by tpluscode** [PolymerElements/test-fixture#38]
### Description

I'm seeing errors when stamping `<test-fixture>` when running tests on Sauce Labs. The error says a variation of

> Tests failed: Error thrown outside of test function: the string "console.error: Error stamping [object Object] NotSupportedError

when the `fixture(id)` function is called

### Actual outcome

Different browsers give different errors but it seems that in some cases, the `<test-fixture>` instance is not being found. [Firefox gives a most descriptive message](https://travis-ci.org/wikibus/augeas#L2081)

> document.getElementById(...).create is not a function

from [this line in code](https://github.com/PolymerElements/test-fixture/blob/master/test-fixture-mocha.js#L31)

### Live Demo
You can see Travis runs of my repositories [here](https://travis-ci.org/wikibus/augeas/builds/1725474170) and [here](https://travis-ci.org/tpluscode/ld-navigation/builds/173386522).

Interestingly the latter suite only fails on Edge and the former gives that same error across all browsers. And none of that happens locally on Chrome, Firefox or IE11.

### Steps to reproduce

Probably the best way is to run manually with Sauce Labs.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [x] IE 11
- [ ] IE 10

**Comment by tpluscode** [comment]
This looks similar to Polymer/test-fixture#16 but I don't understand what the solution to that issue should be.

**Comment by jshcrowthe** [comment]
I have been seeing the same issues with using the full v0 webcomponents polyfill.

For me the issue is isolated to IE11/Edge, all other browsers perform fine.

Travis Builds:
- https://travis-ci.org/jshcrowthe/dialog-el/builds/193632298
- https://travis-ci.org/jshcrowthe/dialog-el/builds/193625081

**Comment by owendismuke** [comment]
I have a similar issue only on IE@11.0.14393.0 using npm WCT@5.0.0 
`"/bower_components/webcomponentsjs/webcomponents-lite.js"  
  "/components/web-component-tester/browser.js"`

```
Error stamping [object HTMLUnknownElement] TypeError: WeakMap.prototype.set: 'key' is not an object
   "Error stamping"
   <template></template>
      description: "WeakMap.prototype.set: 'key' is not an object",
      message: "WeakMap.prototype.set: 'key' is not an object",
      name: "TypeError",
      number: -2146823171,
      stack: "TypeError: WeakMap.prototype.set: 'key' is not an object
   at _recordEventHandler (data:text/javascript;charset=utf-8,Polymer.nar... (long painful stack trace)   }
```
