### ISSUE TITLE
Safari: dom-repeat template inside test-fixture gets no content

### ISSUE THREAD

**Issue by atotic** [PolymerElements/test-fixture#7]
I've just created a pull request with a test case that demonstrates the issue. This causes iron-selector tests to fail.

    <test-fixture id="NestedRepeatFixture">
      <template>
        <template id="repeater" is="dom-repeat">
          <div>{{item}}</div>
        </template>
      </template>
    </test-fixture>

repeater.content will be null on Safari after fixture.create()

**Comment by notwaldorf** [comment]
This is caused by  https://github.com/webcomponents/webcomponentsjs/issues/362. Will be resolved when that's fixed.
