### ISSUE TITLE
Comments within the template tags cause issues

### ISSUE THREAD

**Issue by torcellite** [PolymerElements/test-fixture#9]
The following code:

<b>HTML</b>

    <test-fixture id="active">
        <template>
            
            
            
            <navbar-button _label="Active"></navbar-button>
        </template>
    </test-fixture>

<b>JS</b>

    assert.equal(navButton.getAttribute('_label'), "Active", "_label is not Active");

Causes:

    chrome 43                ✖ views/elements/navbar-button/test/test.html » basic » test fixture active

    navButton.getAttribute is not a function

The comments need to be moved out of the template tags for the error to be resolved.

<b>HTML</b>

    
    
    
    <test-fixture id="active">
        <template>
            <navbar-button _label="Active"></navbar-button>
        </template>
    </test-fixture>

**Comment by cdata** [comment]
This is a great point. We should probably discard `comment` nodes.

**Comment by bicknellr** [comment]
This was fixed by #10; #16 adds a couple tests specifically for this case.

**Comment by bicknellr** [comment]
#16 merged.
